version: '3'

services:

  api:
    build:
      context: node
    container_name: api
    networks:
      - todo-list-network
    tty: true
    depends_on:
      - db
    ports:
      - "3000:3000"

  db:
    build:
      context: mongo
    container_name: db
    restart: always
    user:  "root"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - todo-list-mongodb:/data/db
      - todo-list-mongodb-config:/data/configdb
    networks:
      - todo-list-network
    tty: true
    ports:
      - 27017:27017

networks: 
  todo-list-network:
    driver: bridge

volumes:
  todo-list-mongodb:
  todo-list-mongodb-config:
